type Usuario {
  idade: Int
  salario: Float
  email: String!
  nome: String
  ativo: Boolean
  id: ID
  perfil: Perfil
}

type Query {
  usuarios: [Usuario]
  usuario(id: Int): Usuario
}

type Mutation {
  criarUsuario(
    idade: Int
    salario: Float
    nome: String!
    email: String!
  ): Usuario!
}
