type User {
  id: Int
  login: String
  avatar_url: String
  tasks: [Task]
  token: String
}
input UserFilter {
  id: Int
  avatar_url: String
}
input UserInput {
  login: String
  avatar_url: String
}

type Query {
  users: [User]
  user(login: String): User
}

type Mutation {
  createUser(data: UserInput): User
  updateUser(id: Int!, data: UserInput): User
  deleteUser(filter: UserFilter): Boolean
}
